baseURL = 'https://liongkj.github.io/'
languageCode = 'en-us'
title = 'Liong Khai Jiet'

# Disable default taxonomies
disableKinds = ['taxonomy', 'term']

# Enable emoji support
enableEmoji = false

# Configure markup
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Configure output
[outputs]
  home = ['HTML']

# Permalink configuration
[permalinks]
  page = '/:filename/'
